import "./globals.css";
import type { Metadata } from "next";
import StoreProvider from "./StoreProvider";
import { SocketProvider } from "../contexts/SocketContext";

export const metadata: Metadata = {
  title: "Meet App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <StoreProvider>
          <SocketProvider>
            {children}
          </SocketProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
