FROM node:24-alpine

WORKDIR /app

COPY ./packages ./packages
COPY ./apps/http-backend ./apps/http-backend

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json
COPY ./pnpm-lock.yaml ./pnpm-lock.yaml
COPY ./pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN npm install -g pnpm
RUN pnpm install

RUN pnpm run db:build
RUN pnpm build

EXPOSE 4000

CMD ["pnpm", "run", "start:http-backend"]